import type { Metadata } from "next"
import "./globals.css"
import { Toaster } from "sonner"
import Navbar from "./_components/ui/shared/Navbar/Navbar"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br">
      <body>
        <Navbar />
        <div className="grid grid-flow-col min-h-screen px-12 py-24">
          {children}
        </div>
        <Toaster />
      </body>
    </html>
  )
}
